/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ahb.common.exchange;


public enum ExchangeType implements org.apache.thrift.TEnum {
  JOIN(1),
  EXIT(2),
  HEARTBEAT(3),
  STATUES_TRUE(4),
  STATUES_FALSE(5),
  REQ(6),
  RESP(7),
  IGNORE(8),
  CLEAN_TOKEN(9),
  BIZ_DIS(10);

  private final int value;

  private ExchangeType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ExchangeType findByValue(int value) { 
    switch (value) {
      case 1:
        return JOIN;
      case 2:
        return EXIT;
      case 3:
        return HEARTBEAT;
      case 4:
        return STATUES_TRUE;
      case 5:
        return STATUES_FALSE;
      case 6:
        return REQ;
      case 7:
        return RESP;
      case 8:
        return IGNORE;
      case 9:
        return CLEAN_TOKEN;
      case 10:
        return BIZ_DIS;
      default:
        return null;
    }
  }
}
