/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ahb.common.exchange;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-03-22")
public class JoinReq implements org.apache.thrift.TBase<JoinReq, JoinReq._Fields>, java.io.Serializable, Cloneable, Comparable<JoinReq> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("JoinReq");

  private static final org.apache.thrift.protocol.TField EX_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("exInfo", org.apache.thrift.protocol.TType.STRUCT, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new JoinReqStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new JoinReqTupleSchemeFactory();

  public ExchangeInfo exInfo; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    EX_INFO((short)1, "exInfo");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // EX_INFO
          return EX_INFO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.EX_INFO, new org.apache.thrift.meta_data.FieldMetaData("exInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ExchangeInfo.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(JoinReq.class, metaDataMap);
  }

  public JoinReq() {
  }

  public JoinReq(
    ExchangeInfo exInfo)
  {
    this();
    this.exInfo = exInfo;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public JoinReq(JoinReq other) {
    if (other.isSetExInfo()) {
      this.exInfo = new ExchangeInfo(other.exInfo);
    }
  }

  public JoinReq deepCopy() {
    return new JoinReq(this);
  }

  @Override
  public void clear() {
    this.exInfo = null;
  }

  public ExchangeInfo getExInfo() {
    return this.exInfo;
  }

  public JoinReq setExInfo(ExchangeInfo exInfo) {
    this.exInfo = exInfo;
    return this;
  }

  public void unsetExInfo() {
    this.exInfo = null;
  }

  /** Returns true if field exInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetExInfo() {
    return this.exInfo != null;
  }

  public void setExInfoIsSet(boolean value) {
    if (!value) {
      this.exInfo = null;
    }
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case EX_INFO:
      if (value == null) {
        unsetExInfo();
      } else {
        setExInfo((ExchangeInfo)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case EX_INFO:
      return getExInfo();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case EX_INFO:
      return isSetExInfo();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof JoinReq)
      return this.equals((JoinReq)that);
    return false;
  }

  public boolean equals(JoinReq that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_exInfo = true && this.isSetExInfo();
    boolean that_present_exInfo = true && that.isSetExInfo();
    if (this_present_exInfo || that_present_exInfo) {
      if (!(this_present_exInfo && that_present_exInfo))
        return false;
      if (!this.exInfo.equals(that.exInfo))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetExInfo()) ? 131071 : 524287);
    if (isSetExInfo())
      hashCode = hashCode * 8191 + exInfo.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(JoinReq other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetExInfo()).compareTo(other.isSetExInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.exInfo, other.exInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("JoinReq(");
    boolean first = true;

    sb.append("exInfo:");
    if (this.exInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.exInfo);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (exInfo != null) {
      exInfo.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class JoinReqStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public JoinReqStandardScheme getScheme() {
      return new JoinReqStandardScheme();
    }
  }

  private static class JoinReqStandardScheme extends org.apache.thrift.scheme.StandardScheme<JoinReq> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, JoinReq struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // EX_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.exInfo = new ExchangeInfo();
              struct.exInfo.read(iprot);
              struct.setExInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, JoinReq struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.exInfo != null) {
        oprot.writeFieldBegin(EX_INFO_FIELD_DESC);
        struct.exInfo.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class JoinReqTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public JoinReqTupleScheme getScheme() {
      return new JoinReqTupleScheme();
    }
  }

  private static class JoinReqTupleScheme extends org.apache.thrift.scheme.TupleScheme<JoinReq> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, JoinReq struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetExInfo()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetExInfo()) {
        struct.exInfo.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, JoinReq struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.exInfo = new ExchangeInfo();
        struct.exInfo.read(iprot);
        struct.setExInfoIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

