/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.ahb.common.exchange;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.11.0)", date = "2018-03-14")
public class NodeAxis implements org.apache.thrift.TBase<NodeAxis, NodeAxis._Fields>, java.io.Serializable, Cloneable, Comparable<NodeAxis> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("NodeAxis");

  private static final org.apache.thrift.protocol.TField X_AXIS_FIELD_DESC = new org.apache.thrift.protocol.TField("xAxis", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField Y_AXIS_FIELD_DESC = new org.apache.thrift.protocol.TField("yAxis", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField Z_AXIS_FIELD_DESC = new org.apache.thrift.protocol.TField("zAxis", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField IP_FIELD_DESC = new org.apache.thrift.protocol.TField("ip", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField PORT_FIELD_DESC = new org.apache.thrift.protocol.TField("port", org.apache.thrift.protocol.TType.I32, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new NodeAxisStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new NodeAxisTupleSchemeFactory();

  public int xAxis; // required
  public int yAxis; // required
  public int zAxis; // required
  public java.lang.String ip; // required
  public int port; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    X_AXIS((short)1, "xAxis"),
    Y_AXIS((short)2, "yAxis"),
    Z_AXIS((short)3, "zAxis"),
    IP((short)4, "ip"),
    PORT((short)5, "port");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // X_AXIS
          return X_AXIS;
        case 2: // Y_AXIS
          return Y_AXIS;
        case 3: // Z_AXIS
          return Z_AXIS;
        case 4: // IP
          return IP;
        case 5: // PORT
          return PORT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __XAXIS_ISSET_ID = 0;
  private static final int __YAXIS_ISSET_ID = 1;
  private static final int __ZAXIS_ISSET_ID = 2;
  private static final int __PORT_ISSET_ID = 3;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.X_AXIS, new org.apache.thrift.meta_data.FieldMetaData("xAxis", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.Y_AXIS, new org.apache.thrift.meta_data.FieldMetaData("yAxis", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.Z_AXIS, new org.apache.thrift.meta_data.FieldMetaData("zAxis", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.IP, new org.apache.thrift.meta_data.FieldMetaData("ip", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PORT, new org.apache.thrift.meta_data.FieldMetaData("port", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(NodeAxis.class, metaDataMap);
  }

  public NodeAxis() {
  }

  public NodeAxis(
    int xAxis,
    int yAxis,
    int zAxis,
    java.lang.String ip,
    int port)
  {
    this();
    this.xAxis = xAxis;
    setXAxisIsSet(true);
    this.yAxis = yAxis;
    setYAxisIsSet(true);
    this.zAxis = zAxis;
    setZAxisIsSet(true);
    this.ip = ip;
    this.port = port;
    setPortIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public NodeAxis(NodeAxis other) {
    __isset_bitfield = other.__isset_bitfield;
    this.xAxis = other.xAxis;
    this.yAxis = other.yAxis;
    this.zAxis = other.zAxis;
    if (other.isSetIp()) {
      this.ip = other.ip;
    }
    this.port = other.port;
  }

  public NodeAxis deepCopy() {
    return new NodeAxis(this);
  }

  @Override
  public void clear() {
    setXAxisIsSet(false);
    this.xAxis = 0;
    setYAxisIsSet(false);
    this.yAxis = 0;
    setZAxisIsSet(false);
    this.zAxis = 0;
    this.ip = null;
    setPortIsSet(false);
    this.port = 0;
  }

  public int getXAxis() {
    return this.xAxis;
  }

  public NodeAxis setXAxis(int xAxis) {
    this.xAxis = xAxis;
    setXAxisIsSet(true);
    return this;
  }

  public void unsetXAxis() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __XAXIS_ISSET_ID);
  }

  /** Returns true if field xAxis is set (has been assigned a value) and false otherwise */
  public boolean isSetXAxis() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __XAXIS_ISSET_ID);
  }

  public void setXAxisIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __XAXIS_ISSET_ID, value);
  }

  public int getYAxis() {
    return this.yAxis;
  }

  public NodeAxis setYAxis(int yAxis) {
    this.yAxis = yAxis;
    setYAxisIsSet(true);
    return this;
  }

  public void unsetYAxis() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __YAXIS_ISSET_ID);
  }

  /** Returns true if field yAxis is set (has been assigned a value) and false otherwise */
  public boolean isSetYAxis() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __YAXIS_ISSET_ID);
  }

  public void setYAxisIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __YAXIS_ISSET_ID, value);
  }

  public int getZAxis() {
    return this.zAxis;
  }

  public NodeAxis setZAxis(int zAxis) {
    this.zAxis = zAxis;
    setZAxisIsSet(true);
    return this;
  }

  public void unsetZAxis() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ZAXIS_ISSET_ID);
  }

  /** Returns true if field zAxis is set (has been assigned a value) and false otherwise */
  public boolean isSetZAxis() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ZAXIS_ISSET_ID);
  }

  public void setZAxisIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ZAXIS_ISSET_ID, value);
  }

  public java.lang.String getIp() {
    return this.ip;
  }

  public NodeAxis setIp(java.lang.String ip) {
    this.ip = ip;
    return this;
  }

  public void unsetIp() {
    this.ip = null;
  }

  /** Returns true if field ip is set (has been assigned a value) and false otherwise */
  public boolean isSetIp() {
    return this.ip != null;
  }

  public void setIpIsSet(boolean value) {
    if (!value) {
      this.ip = null;
    }
  }

  public int getPort() {
    return this.port;
  }

  public NodeAxis setPort(int port) {
    this.port = port;
    setPortIsSet(true);
    return this;
  }

  public void unsetPort() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PORT_ISSET_ID);
  }

  /** Returns true if field port is set (has been assigned a value) and false otherwise */
  public boolean isSetPort() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PORT_ISSET_ID);
  }

  public void setPortIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PORT_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case X_AXIS:
      if (value == null) {
        unsetXAxis();
      } else {
        setXAxis((java.lang.Integer)value);
      }
      break;

    case Y_AXIS:
      if (value == null) {
        unsetYAxis();
      } else {
        setYAxis((java.lang.Integer)value);
      }
      break;

    case Z_AXIS:
      if (value == null) {
        unsetZAxis();
      } else {
        setZAxis((java.lang.Integer)value);
      }
      break;

    case IP:
      if (value == null) {
        unsetIp();
      } else {
        setIp((java.lang.String)value);
      }
      break;

    case PORT:
      if (value == null) {
        unsetPort();
      } else {
        setPort((java.lang.Integer)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case X_AXIS:
      return getXAxis();

    case Y_AXIS:
      return getYAxis();

    case Z_AXIS:
      return getZAxis();

    case IP:
      return getIp();

    case PORT:
      return getPort();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case X_AXIS:
      return isSetXAxis();
    case Y_AXIS:
      return isSetYAxis();
    case Z_AXIS:
      return isSetZAxis();
    case IP:
      return isSetIp();
    case PORT:
      return isSetPort();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof NodeAxis)
      return this.equals((NodeAxis)that);
    return false;
  }

  public boolean equals(NodeAxis that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_xAxis = true;
    boolean that_present_xAxis = true;
    if (this_present_xAxis || that_present_xAxis) {
      if (!(this_present_xAxis && that_present_xAxis))
        return false;
      if (this.xAxis != that.xAxis)
        return false;
    }

    boolean this_present_yAxis = true;
    boolean that_present_yAxis = true;
    if (this_present_yAxis || that_present_yAxis) {
      if (!(this_present_yAxis && that_present_yAxis))
        return false;
      if (this.yAxis != that.yAxis)
        return false;
    }

    boolean this_present_zAxis = true;
    boolean that_present_zAxis = true;
    if (this_present_zAxis || that_present_zAxis) {
      if (!(this_present_zAxis && that_present_zAxis))
        return false;
      if (this.zAxis != that.zAxis)
        return false;
    }

    boolean this_present_ip = true && this.isSetIp();
    boolean that_present_ip = true && that.isSetIp();
    if (this_present_ip || that_present_ip) {
      if (!(this_present_ip && that_present_ip))
        return false;
      if (!this.ip.equals(that.ip))
        return false;
    }

    boolean this_present_port = true;
    boolean that_present_port = true;
    if (this_present_port || that_present_port) {
      if (!(this_present_port && that_present_port))
        return false;
      if (this.port != that.port)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + xAxis;

    hashCode = hashCode * 8191 + yAxis;

    hashCode = hashCode * 8191 + zAxis;

    hashCode = hashCode * 8191 + ((isSetIp()) ? 131071 : 524287);
    if (isSetIp())
      hashCode = hashCode * 8191 + ip.hashCode();

    hashCode = hashCode * 8191 + port;

    return hashCode;
  }

  @Override
  public int compareTo(NodeAxis other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetXAxis()).compareTo(other.isSetXAxis());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetXAxis()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.xAxis, other.xAxis);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetYAxis()).compareTo(other.isSetYAxis());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetYAxis()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.yAxis, other.yAxis);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetZAxis()).compareTo(other.isSetZAxis());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetZAxis()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.zAxis, other.zAxis);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetIp()).compareTo(other.isSetIp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ip, other.ip);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetPort()).compareTo(other.isSetPort());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPort()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.port, other.port);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("NodeAxis(");
    boolean first = true;

    sb.append("xAxis:");
    sb.append(this.xAxis);
    first = false;
    if (!first) sb.append(", ");
    sb.append("yAxis:");
    sb.append(this.yAxis);
    first = false;
    if (!first) sb.append(", ");
    sb.append("zAxis:");
    sb.append(this.zAxis);
    first = false;
    if (!first) sb.append(", ");
    sb.append("ip:");
    if (this.ip == null) {
      sb.append("null");
    } else {
      sb.append(this.ip);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("port:");
    sb.append(this.port);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class NodeAxisStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public NodeAxisStandardScheme getScheme() {
      return new NodeAxisStandardScheme();
    }
  }

  private static class NodeAxisStandardScheme extends org.apache.thrift.scheme.StandardScheme<NodeAxis> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, NodeAxis struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // X_AXIS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.xAxis = iprot.readI32();
              struct.setXAxisIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // Y_AXIS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.yAxis = iprot.readI32();
              struct.setYAxisIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // Z_AXIS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.zAxis = iprot.readI32();
              struct.setZAxisIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // IP
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ip = iprot.readString();
              struct.setIpIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // PORT
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.port = iprot.readI32();
              struct.setPortIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, NodeAxis struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(X_AXIS_FIELD_DESC);
      oprot.writeI32(struct.xAxis);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(Y_AXIS_FIELD_DESC);
      oprot.writeI32(struct.yAxis);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(Z_AXIS_FIELD_DESC);
      oprot.writeI32(struct.zAxis);
      oprot.writeFieldEnd();
      if (struct.ip != null) {
        oprot.writeFieldBegin(IP_FIELD_DESC);
        oprot.writeString(struct.ip);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(PORT_FIELD_DESC);
      oprot.writeI32(struct.port);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class NodeAxisTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public NodeAxisTupleScheme getScheme() {
      return new NodeAxisTupleScheme();
    }
  }

  private static class NodeAxisTupleScheme extends org.apache.thrift.scheme.TupleScheme<NodeAxis> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, NodeAxis struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetXAxis()) {
        optionals.set(0);
      }
      if (struct.isSetYAxis()) {
        optionals.set(1);
      }
      if (struct.isSetZAxis()) {
        optionals.set(2);
      }
      if (struct.isSetIp()) {
        optionals.set(3);
      }
      if (struct.isSetPort()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetXAxis()) {
        oprot.writeI32(struct.xAxis);
      }
      if (struct.isSetYAxis()) {
        oprot.writeI32(struct.yAxis);
      }
      if (struct.isSetZAxis()) {
        oprot.writeI32(struct.zAxis);
      }
      if (struct.isSetIp()) {
        oprot.writeString(struct.ip);
      }
      if (struct.isSetPort()) {
        oprot.writeI32(struct.port);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, NodeAxis struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        struct.xAxis = iprot.readI32();
        struct.setXAxisIsSet(true);
      }
      if (incoming.get(1)) {
        struct.yAxis = iprot.readI32();
        struct.setYAxisIsSet(true);
      }
      if (incoming.get(2)) {
        struct.zAxis = iprot.readI32();
        struct.setZAxisIsSet(true);
      }
      if (incoming.get(3)) {
        struct.ip = iprot.readString();
        struct.setIpIsSet(true);
      }
      if (incoming.get(4)) {
        struct.port = iprot.readI32();
        struct.setPortIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

